// Datos de ejemplo para miembros
export const mockMembers = [
  {
    id: "1",
    name: "Juan Pérez",
    dni: "12345678",
    email: "juan.perez@ejemplo.com",
    phone: "+34 612 345 678",
    plan: "Premium",
    startDate: "15/01/2023",
    endDate: "15/12/2023",
  },
]

// Datos de ejemplo para pagos
export const mockPayments = [
  {
    id: "1",
    member: "Juan Pérez",
    date: "15/01/2023",
    time: "10:30",
    amount: 80,
    method: "Tarjeta de Crédito",
    recordedBy: "Admin",
    shift: "mañana",
    concept: "Mensualidad Premium",
  },
  {
    id: "2",
    member: "María García",
    date: "10/02/2023",
    time: "16:45",
    amount: 50,
    method: "Tarjeta de Débito",
    recordedBy: "Recepcionista",
    shift: "tarde",
    concept: "Mensualidad Estándar",
  },
  {
    id: "3",
    member: "David Rodríguez",
    date: "05/03/2023",
    time: "09:15",
    amount: 30,
    method: "Efectivo",
    recordedBy: "Recepcionista",
    shift: "mañana",
    concept: "Mensualidad Básica",
  },
  {
    id: "4",
    member: "Sara Martínez",
    date: "20/01/2023",
    time: "11:20",
    amount: 80,
    method: "Transferencia Bancaria",
    recordedBy: "Admin",
    shift: "mañana",
    concept: "Mensualidad Premium",
  },
  {
    id: "5",
    member: "Miguel López",
    date: "15/02/2023",
    time: "18:30",
    amount: 50,
    method: "Tarjeta de Crédito",
    recordedBy: "Recepcionista",
    shift: "tarde",
    concept: "Mensualidad Estándar",
  },
  {
    id: "6",
    member: "Jennifer Sánchez",
    date: "10/03/2023",
    time: "20:15",
    amount: 30,
    method: "Efectivo",
    recordedBy: "Recepcionista",
    shift: "noche",
    concept: "Mensualidad Básica",
  },
  {
    id: "7",
    member: "Roberto Fernández",
    date: "25/01/2023",
    time: "12:45",
    amount: 80,
    method: "Tarjeta de Débito",
    recordedBy: "Admin",
    shift: "mañana",
    concept: "Mensualidad Premium",
  },
  {
    id: "8",
    member: "Laura González",
    date: "20/02/2023",
    time: "17:10",
    amount: 50,
    method: "Transferencia Bancaria",
    recordedBy: "Recepcionista",
    shift: "tarde",
    concept: "Mensualidad Estándar",
  },
]

// Datos de ejemplo para perfil de miembro
export const mockMemberProfile = {
  id: "1",
  name: "Juan Pérez",
  email: "juan.perez@ejemplo.com",
  phone: "+34 612 345 678",
  plan: "Premium",
  planPrice: 80,
  startDate: "15/01/2023",
  endDate: "15/12/2023",
  remainingClasses: 8,
  totalClasses: 12,
}

// Datos de ejemplo para pagos de miembro
export const mockMemberPayments = [
  {
    id: "1",
    date: "15/01/2023",
    description: "Membresía Premium - Anual",
    amount: 960,
    method: "Tarjeta de Crédito",
    status: "completed",
  },
  {
    id: "2",
    date: "15/02/2023",
    description: "Sesión de Entrenamiento Personal",
    amount: 50,
    method: "Tarjeta de Crédito",
    status: "completed",
  },
  {
    id: "3",
    date: "10/03/2023",
    description: "Consulta de Nutrición",
    amount: 75,
    method: "Tarjeta de Débito",
    status: "completed",
  },
  {
    id: "4",
    date: "05/04/2023",
    description: "Compra de Merchandising",
    amount: 35,
    method: "Efectivo",
    status: "completed",
  },
  {
    id: "5",
    date: "20/05/2023",
    description: "Paquete de Clases Grupales",
    amount: 120,
    method: "Transferencia Bancaria",
    status: "pending",
  },
]

